services:
  frontend:
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/srv
    command: sh -c "npm install && npm run dev"
    environment:
      - API_BASE_URL=http://localhost:8200
